name: ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.2.3
  iconsax: ^0.0.8
  pinput: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/categoris/
    - assets/Beverages/
  fonts:
    - family: AlegreyaSC
      fonts:
        - asset: assets/fonts/AlegreyaSC-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins-Bold.ttf
        - asset: assets/fonts/poppins-Light.ttf